In [ ]:
import torch
torch.__version__


'2.5.1+cu124'

In [ ]:
#Sclar and vector in Tensor
scalar = torch.tensor(1)
#Scalar is 0 dimension tensor
#ndim can be used to know the dimension of a tensor
scalar.ndim

0

Vector is the tensor with single dimesion

In [ ]:
vector = torch.tensor([1,2])
#vector is defines with square braces and its number can define the dimension of the vector.
#The representation of vector is flexible
vector.ndim

1

In [ ]:
#shape of the vector is defined as the number of elements that are present inside the vector
#The shape of vector is [2]
vector.shape

torch.Size([2])

In [ ]:
#Matrix is tensor with dimension 2
MATRIX = torch.tensor([[2,3],[6,4]])
MATRIX.ndim
#The side of matrix is [2,2] here 2 element deep and two element wide
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSOR=torch.tensor([[[2,3],[5,9],[8,2]]])
TENSOR.ndim
TENSOR.shape
#The size is [1,3,2] and goes from outer to inner

torch.Size([1, 3, 2])

scalar and vector are represented with lowercase and MATRIX and TENSOR are represented with uppercase.
# Random Tensors



In [ ]:
#providing dimension and generating random tensor using rand
random_tensor = torch.rand(size=(2,3))
random_tensor, random_tensor.shape, random_tensor.dtype

(tensor([[0.8294, 0.9190, 0.3334],
         [0.1793, 0.3641, 0.7889]]),
 torch.Size([2, 3]),
 torch.float32)

In [ ]:
pic_tensor = torch.rand(size=(144,144,3))
# pic_tensor, pic_tensor.ndim

# Zeros and Ones
Zeros and ones are used during masking as we have to train model not to use the certain features or tensors.

In [ ]:
zeros = torch.zeros(size=(2,3))
zeros
ones = torch.ones(size=(2,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

# Range in Tensor

In [ ]:
range_tensor = torch.arange(0,10,2)
range_tensor


tensor([0, 2, 4, 6, 8])

In [ ]:
#can create tensors of zeros similar to other tensor
zeros_tensor = torch.zeros_like(input=range_tensor)
zeros_tensor

tensor([0, 0, 0, 0, 0])

#Datatype and device in Tensors
Datatype in a tensor and device of tensor matters as the operation is done with the tensor of similar dataype and similar device

In [ ]:
#float32 is the default size of tensor datatype and device is cpu
float_datatype_tensor = torch.tensor([1.0, 2.0, 3.0],
                                     dtype=None,
                                     device=None)
float_datatype_tensor.dtype, float_datatype_tensor.device
float_16_tensor = torch.tensor([2.0, 3.0, 4.0], dtype=torch.float16)
float_16_tensor

tensor([2., 3., 4.], dtype=torch.float16)

# Basic opeations in Tensors

In [ ]:
a_tensor = torch.tensor([3,4,5])
a_tensor + 10
a_tensor * 2
#only change when assigned
a_tensor
b_tensor = a_tensor + 2
#we can also use torch function for multiplication and addition
c_tensor = torch.multiply(a_tensor, 20)
c_tensor
#Elementwise multiplication can also as "*"


tensor([ 60,  80, 100])