<a href="https://colab.research.google.com/github/Bishalnpn/pytorch_fundamentals/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
torch.__version__


'2.5.1+cu124'

In [12]:
x = torch.tensor([1.0,2.0], requires_grad=True)
y = x.detach()
y[1] = 3.0
print(x)
print(y)

print(y.requires_grad)

tensor([1., 3.], requires_grad=True)
tensor([1., 3.])
False


In [11]:
print(x)

tensor([1., 2.], requires_grad=True)
